name: Common Test Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  # Job pour les tests unitaires (npm test)
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests (npm test)
        run: npm test

  # Job pour les tests E2E avec Cypress
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Cache Cypress binary (only if requested)
        if: ${{ inputs.use_cypress_cache == true }}
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v13-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cypress-cache-v13-${{ runner.os }}-

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run E2E tests with Cypress
        run: npx cypress run