name: E2E Tests

on: [push, pull_request]

jobs:
  test:
    uses: owner/repository/.github/workflows/common-tests.yml@main
    with:
      node_version: '20'
      test_command: 'npx cypress run'
      use_cypress_cache: 'true'